"""
Create a program that will play the “cows and bulls” game with the user. The game works like this:

Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. For every digit that the user guessed correctly in the correct place, they have a “cow”. For every digit the user guessed correctly in the wrong place is a “bull.” Every time the user makes a guess, tell them how many “cows” and “bulls” they have. Once the user guesses the correct number, the game is over. Keep track of the number of guesses the user makes throughout teh game and tell the user at the end.

Say the number generated by the computer is 1038. An example interaction could look like this:

  Welcome to the Cows and Bulls Game! 
  Enter a number: 
  >>> 1234
  2 cows, 0 bulls
  >>> 1256
  1 cow, 1 bull
  ...
Until the user guesses the number.
"""

import random

def main(num_to_guess, user_number):
    count = 1
    while num_to_guess != user_number:
        cows = sum(1 for guess, user in zip(num_to_guess, user_number) if guess == user)
        print(f'\nYou got {cows} cows and {4 - cows} bulls, try again...\n')
        count += 1
        user_number = ask_number()
    return count
    

def welcome():
    print(f'\n{"*" * 70}\n\n\tWelcome to the Cows and Bulls Game\n\n> To won you need to guess the 4 digit number in the less tries as possible.\n> Every time you guess correctly and in the right place a number, the game will returns "Cows"\n> Otherwise, it will print "Bull" if you guessed wrong\n\n{"*" * 70}\n\nAre you ready?...\n\n')


def guess_what():
    
    # We convert the random number to string in a list to zipped later
    num_to_guess = [str(random.randint(0, 9)) for i in range(4)]
    # print(f'this is the nunber to guess: {num_to_guess} but shhhh!')

    # If the random number start with 0 we choice a new number
    if num_to_guess[0] == 0:
        guess_what()
    else:
        return num_to_guess

def ask_number():
    user_number = input('Enter a 4 digit number: ')
    user_number = [x for x in user_number]

    print(f'The user number is {user_number}')
    return user_number


if __name__ == '__main__':
    welcome()
    num_to_guess = guess_what()
    user_number = ask_number()
    win = main(num_to_guess, user_number)
    print(f'You win! and play {win} rounds, Game Over')